[package]
name = "coproduct-idtype-macro"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "a proc macro for the coproduct crate"
repository = "https://github.com/joonazan/coproduct/tree/master/idtype_macro"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = "1.0"
